import { StyleSheet } from "react-native";
import { C } from "./dashboard.styles";

export default StyleSheet.create({
  safe:   { flex: 1, backgroundColor: C.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 52,
    paddingBottom: 4,
  },
  title: {
    fontSize: 28, fontWeight: "700", color: C.text, letterSpacing: -0.5,
  },
  menuBtn: {
    padding: 6, borderRadius: 8,
    backgroundColor: C.surface, borderWidth: 1, borderColor: C.border,
  },

  pillRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingTop: 16, paddingBottom: 14,
    gap: 8,
  },
  pill: {
    paddingHorizontal: 18, paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: C.surface,
    borderWidth: 1, borderColor: C.border,
  },
  pillActive: { backgroundColor: "#fff", borderColor: "#fff" },
  pillTxt: { fontSize: 13, fontWeight: "500", color: C.soft },
  pillTxtActive: { color: "#000", fontWeight: "700" },

  scroll: { paddingHorizontal: 14, paddingBottom: 48, gap: 14 },

  heroCard: {
    backgroundColor: C.surface,
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 18,
    gap: 14,
    overflow: "hidden",
  },
  heroGlow: {
    position: "absolute",
    top: -80, right: -80,
    width: 200, height: 200,
    borderRadius: 100,
    opacity: 0.1,
  },
  heroTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  heroLabelRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 },
  heroDot: { width: 7, height: 7, borderRadius: 4 },
  heroLabel: {
    fontSize: 11, color: C.soft,
    letterSpacing: 0.6, textTransform: "uppercase",
    fontWeight: "600",
  },
  heroNum: {
    fontSize: 56, fontWeight: "300",
    letterSpacing: -2, lineHeight: 60,
  },
  heroUnit: { fontSize: 18, fontWeight: "500", color: C.soft, letterSpacing: 0 },

  diffBadge: {
    flexDirection: "row", alignItems: "center", gap: 3,
    paddingHorizontal: 10, paddingVertical: 5,
    borderRadius: 999, borderWidth: 1,
    marginTop: 4,
  },
  diffTxt: { fontSize: 12, fontWeight: "700" },

  chartWrap: {
    marginVertical: 4,
  },

  chartTypeRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
  },
  typeBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.raised,
  },
  typeBtnTxt: { fontSize: 12, color: C.soft, fontWeight: "600" },

  heroFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1, borderTopColor: C.border,
    paddingTop: 12, marginTop: 2,
  },
  footerStat: { flexDirection: "row", alignItems: "center", gap: 5 },
  footerTxt: { fontSize: 11, color: C.soft, fontWeight: "500" },

  sectionLabel: {
    fontSize: 10, fontWeight: "700",
    color: C.soft, letterSpacing: 1.2,
    paddingHorizontal: 4, marginTop: 4,
  },

  metricScroll: {
    paddingHorizontal: 4, paddingVertical: 4, gap: 7,
  },
  metricChip: {
    flexDirection: "row", alignItems: "center", gap: 6,
    paddingHorizontal: 12, paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: C.surface,
    borderWidth: 1.2,
  },
  metricDot: { width: 7, height: 7, borderRadius: 4 },
  metricChipTxt: { fontSize: 12.5, color: C.text, fontWeight: "600" },

  legendScroll: {
    paddingTop: 8, gap: 6,
  },
  legendChip: {
    flexDirection: "row", alignItems: "center", gap: 6,
    paddingHorizontal: 10, paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1, borderColor: C.border,
    backgroundColor: C.raised,
  },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendLabel: { fontSize: 12, color: C.text, fontWeight: "500" },

  tooltip: {
    flexDirection: "row", alignItems: "center", gap: 10,
    paddingHorizontal: 12, paddingVertical: 9,
    backgroundColor: C.raised,
    borderRadius: 10,
    borderWidth: 1, borderColor: C.border,
    marginTop: 2,
  },
  tooltipDot: { width: 10, height: 10, borderRadius: 5 },
  tooltipTitle: { fontSize: 13, color: C.text, fontWeight: "700" },
  tooltipSub:   { fontSize: 11, color: C.soft, marginTop: 1 },
  tooltipX: {
    width: 22, height: 22, borderRadius: 11,
    alignItems: "center", justifyContent: "center",
    backgroundColor: C.surface, borderWidth: 1, borderColor: C.border,
  },

  pieLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
  },
  pieLegendItem: {
    flexDirection: "row", alignItems: "center", gap: 6,
    paddingHorizontal: 10, paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1, borderColor: C.border,
    backgroundColor: C.raised,
  },
  pieDot: { width: 8, height: 8, borderRadius: 4 },
  pieLegendLabel: { fontSize: 12, color: C.text, fontWeight: "500" },
  pieLegendPct:   { fontSize: 12, fontWeight: "700" },

  macroSection: { gap: 8 },
  macroRow: { flexDirection: "row", gap: 8 },
  macroCard: {
    flex: 1,
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1.2,
    padding: 14, paddingTop: 18,
    gap: 8,
    overflow: "hidden",
  },
  macroAccent: {
    position: "absolute",
    top: 0, left: 0, right: 0,
    height: 3,
  },
  macroLabel: { fontSize: 11, color: C.soft, fontWeight: "600", letterSpacing: 0.4, textTransform: "uppercase" },
  macroVal:   { fontSize: 28, fontWeight: "300", letterSpacing: -0.5 },
  macroUnit:  { fontSize: 13, fontWeight: "500", color: C.soft },
  macroTrack: { height: 4, backgroundColor: C.raised, borderRadius: 2, overflow: "hidden" },
  macroFill:  { height: 4, borderRadius: 2 },
  macroGoal:  { fontSize: 10, color: C.faint },

  microCard: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderWidth: 1, borderColor: C.border,
    padding: 16,
  },
  microRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 4 },
  microDot: { width: 8, height: 8, borderRadius: 4 },
  microSep: { height: 1, backgroundColor: C.border, marginVertical: 10, marginLeft: 20 },
  microLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
  },
  microLabel: { fontSize: 13, color: C.text, fontWeight: "500" },
  microVal: {
    fontSize: 13, fontWeight: "700",
    color: C.text, fontVariant: ["tabular-nums"],
  },
  microUnit: { fontSize: 11, fontWeight: "400", color: C.faint },
  microTrack: {
    height: 4, backgroundColor: C.raised,
    borderRadius: 2, overflow: "hidden",
    marginTop: 6,
  },
  microFill: { height: 4, borderRadius: 2 },
  microGoal: { fontSize: 10, color: C.faint, marginTop: 4 },

  errTxt: { fontSize: 14, color: C.soft },
  retryBtn: {
    paddingHorizontal: 16, paddingVertical: 9,
    borderRadius: 8, borderWidth: 1, borderColor: C.border,
    backgroundColor: C.surface,
  },
  retryTxt: { fontSize: 13, color: C.soft },

  aiSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 2,
  },
  aiSectionTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiSectionTitleTxt: {
    fontSize: 13,
    fontWeight: "700",
    color: C.text,
    letterSpacing: 0.3,
  },
  aiBadge: {
    paddingHorizontal: 7, paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(80,128,188,0.15)",
    borderWidth: 1, borderColor: "rgba(80,128,188,0.4)",
  },
  aiBadgeTxt: {
    fontSize: 9, fontWeight: "700", color: "#7AB0E0",
    letterSpacing: 0.6,
  },
  aiRefreshBtn: {
    width: 28, height: 28,
    borderRadius: 14,
    alignItems: "center", justifyContent: "center",
    backgroundColor: C.surface,
    borderWidth: 1, borderColor: C.border,
  },

  aiTabRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
    marginBottom: 4,
  },
  aiTabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 10,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  aiTabBtnActive: {
    backgroundColor: C.raised,
    borderColor: "#5080BC",
  },
  aiTabBtnTxt: { fontSize: 11.5, color: C.soft, fontWeight: "600" },
  aiTabBtnTxtActive: { color: C.text, fontWeight: "700" },
  aiTabCount: {
    fontSize: 9, fontWeight: "700",
    color: C.faint,
    backgroundColor: C.bg,
    borderRadius: 999,
    paddingHorizontal: 6, paddingVertical: 1,
    overflow: "hidden",
    minWidth: 16,
    textAlign: "center",
  },
  aiTabCountActive: { color: "#7AB0E0", backgroundColor: "rgba(80,128,188,0.18)" },

  scoreCard: {
    backgroundColor: C.surface,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: C.border,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    overflow: "hidden",
  },
  scoreRing: {
    width: 86, height: 86,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  scoreNum: {
    fontSize: 32,
    fontWeight: "700",
    letterSpacing: -1,
  },
  scoreSlash: {
    fontSize: 11, color: C.faint, fontWeight: "500",
    marginTop: -2,
  },
  scoreTextBlock: { flex: 1 },
  scoreLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: C.text,
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  scoreDesc: { fontSize: 12, color: C.soft, lineHeight: 16, fontWeight: "400" },

  insightCard: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 10,
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  insightLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  insightDot: { width: 9, height: 9, borderRadius: 5 },
  insightLabel: {
    fontSize: 11, fontWeight: "700", color: C.soft,
    letterSpacing: 0.7, textTransform: "uppercase",
  },
  insightStatusPill: {
    paddingHorizontal: 9, paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  insightStatusTxt: { fontSize: 10, fontWeight: "700", letterSpacing: 0.5, textTransform: "uppercase" },
  insightProgressTrack: {
    height: 6,
    backgroundColor: C.raised,
    borderRadius: 3,
    overflow: "hidden",
    position: "relative",
  },
  insightProgressFill: { height: 6, borderRadius: 3 },
  insightProgressTarget: {
    position: "absolute",
    top: -3, bottom: -3,
    width: 2,
    backgroundColor: "#fff",
    opacity: 0.6,
  },
  insightStatRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 12,
    marginTop: 4,
  },
  insightStatBig: {
    fontSize: 28, fontWeight: "300",
    letterSpacing: -1,
    fontVariant: ["tabular-nums"],
  },
  insightStatUnit: { fontSize: 13, color: C.soft, fontWeight: "500" },
  insightStatVs: { fontSize: 11, color: C.faint, fontWeight: "500" },
  insightStatGoal: { fontSize: 13, color: C.text, fontWeight: "600" },
  insightExplain: {
    fontSize: 13, color: C.text, lineHeight: 19,
    fontWeight: "400",
    marginTop: 2,
  },

  aiCardBase: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
  },

  winsHScroll: {
    paddingVertical: 4,
    gap: 10,
  },
  winCard: {
    width: 240,
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(81,207,102,0.25)",
    padding: 14,
    gap: 8,
  },
  winIconWrap: {
    width: 30, height: 30, borderRadius: 15,
    backgroundColor: "rgba(81,207,102,0.15)",
    alignItems: "center", justifyContent: "center",
  },
  winTitle: {
    fontSize: 14, fontWeight: "700",
    color: C.text, letterSpacing: -0.2,
  },
  winDetail: {
    fontSize: 12, color: C.soft, lineHeight: 17,
    fontWeight: "400",
  },
  winNutrients: {
    flexDirection: "row", flexWrap: "wrap", gap: 4,
    marginTop: 2,
  },
  winNutChip: {
    paddingHorizontal: 7, paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: C.raised,
    borderWidth: 1, borderColor: C.border,
  },
  winNutChipTxt: {
    fontSize: 10, fontWeight: "600", color: C.soft,
    letterSpacing: 0.2,
  },

  patternCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    flexDirection: "row",
    gap: 12,
    marginBottom: 8,
  },
  patternIconWrap: {
    width: 36, height: 36, borderRadius: 18,
    alignItems: "center", justifyContent: "center",
  },
  patternBody: { flex: 1, gap: 4 },
  patternTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  patternTitle: {
    flex: 1,
    fontSize: 14, fontWeight: "700",
    color: C.text, letterSpacing: -0.2,
  },
  severityPill: {
    paddingHorizontal: 8, paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
  },
  severityPillTxt: { fontSize: 10, fontWeight: "700", letterSpacing: 0.4, textTransform: "uppercase" },
  patternObs: {
    fontSize: 12.5, color: C.soft, lineHeight: 17,
    fontWeight: "400",
    marginTop: 2,
  },
  patternImpact: {
    flexDirection: "row", flexWrap: "wrap", gap: 4,
    marginTop: 4,
  },

  suggestionCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    gap: 9,
    marginBottom: 8,
    overflow: "hidden",
  },
  suggestionHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  rankBadge: {
    width: 28, height: 28, borderRadius: 8,
    alignItems: "center", justifyContent: "center",
    backgroundColor: C.raised,
    borderWidth: 1, borderColor: C.border,
  },
  rankBadgeTxt: { fontSize: 12, fontWeight: "700", color: C.soft },
  suggestionTitle: {
    flex: 1,
    fontSize: 14, fontWeight: "700",
    color: C.text,
    letterSpacing: -0.2,
    lineHeight: 18,
  },
  difficultyPill: {
    paddingHorizontal: 8, paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
  },
  difficultyTxt: { fontSize: 10, fontWeight: "700", letterSpacing: 0.4, textTransform: "uppercase" },

  suggestionLabel: {
    fontSize: 9, fontWeight: "700",
    color: C.faint, letterSpacing: 0.8,
  },
  suggestionBody: {
    fontSize: 12.5, color: C.text, lineHeight: 18,
    fontWeight: "400",
  },
  suggestionDivider: { height: 1, backgroundColor: C.border, marginVertical: 1 },
  impactRow: {
    flexDirection: "row", alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  impactLabel: { fontSize: 10, fontWeight: "700", color: C.faint, letterSpacing: 0.6 },
  impactBar: {
    flex: 1,
    flexDirection: "row",
    gap: 2,
    marginLeft: 10,
  },
  impactDot: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },

  watchCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    gap: 8,
    marginBottom: 8,
  },
  watchHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  watchIconWrap: {
    width: 32, height: 32, borderRadius: 16,
    alignItems: "center", justifyContent: "center",
  },
  watchHeadText: { flex: 1 },
  watchNutrient: {
    fontSize: 13, fontWeight: "700",
    color: C.text, letterSpacing: -0.2,
  },
  watchDir: {
    fontSize: 11, color: C.soft,
    fontWeight: "500",
    marginTop: 1,
  },
  watchMessage: {
    fontSize: 12.5, color: C.text, lineHeight: 17,
    fontWeight: "400",
  },
  watchFoodRow: { flexDirection: "row", gap: 6, alignItems: "flex-start", marginTop: 2 },
  watchFoodLabel: {
    fontSize: 9, fontWeight: "700",
    color: C.faint, letterSpacing: 0.6,
    marginTop: 2,
  },
  watchFoodChips: {
    flex: 1,
    flexDirection: "row", flexWrap: "wrap", gap: 4,
  },
  watchFoodChip: {
    paddingHorizontal: 7, paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: C.raised,
    borderWidth: 1, borderColor: C.border,
  },
  watchFoodChipTxt: { fontSize: 10, color: C.soft, fontWeight: "500" },

  bottomLineCard: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderLeftWidth: 3,
    borderLeftColor: "#5080BC",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: C.border,
    borderRightColor: C.border,
    borderBottomColor: C.border,
    padding: 16,
    gap: 8,
  },
  bottomLineLabel: {
    fontSize: 10, fontWeight: "700",
    color: "#7AB0E0", letterSpacing: 0.8,
  },
  bottomLineBody: {
    fontSize: 13.5, color: C.text, lineHeight: 19,
    fontWeight: "400",
  },
  disclaimer: {
    fontSize: 10, color: C.faint,
    fontStyle: "italic",
    lineHeight: 14,
    marginTop: 6,
  },

  aiSkeleton: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderWidth: 1, borderColor: C.border,
    padding: 18,
    overflow: "hidden",
    gap: 14,
  },
  aiSkeletonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  aiSkeletonCircle: {
    width: 56, height: 56, borderRadius: 28,
    backgroundColor: C.raised,
  },
  aiSkeletonBlock: {
    height: 12,
    borderRadius: 6,
    backgroundColor: C.raised,
  },
  aiSkeletonStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 4,
  },
  aiSkeletonText: { fontSize: 12, color: C.soft, fontWeight: "500", letterSpacing: 0.3 },

  aiErrorCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1, borderColor: C.border,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  aiErrorTxtWrap: { flex: 1 },
  aiErrorTitle: { fontSize: 13, fontWeight: "700", color: C.text },
  aiErrorSub: { fontSize: 11, color: C.soft, marginTop: 2 },

  emptyAiCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1, borderColor: C.border,
    padding: 24,
    alignItems: "center",
    gap: 8,
  },
  emptyAiTitle: { fontSize: 14, fontWeight: "600", color: C.soft },
  emptyAiSub: { fontSize: 12, color: C.faint, textAlign: "center", lineHeight: 17 },

  aiBanner: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(80,128,188,0.55)",
    padding: 16,
    gap: 12,
    overflow: "hidden",
  },
  aiBannerGlow: {
    position: "absolute",
    top: -50, right: -50,
    width: 140, height: 140,
    borderRadius: 70,
    backgroundColor: "#5080BC",
    opacity: 0.08,
  },
  aiBannerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  aiBannerIconWrap: {
    width: 36, height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(80,128,188,0.18)",
    borderWidth: 1, borderColor: "rgba(80,128,188,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  aiBannerHeader: { flex: 1 },
  aiBannerTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: C.text,
    letterSpacing: -0.2,
  },
  aiBannerSub: {
    fontSize: 12,
    color: C.soft,
    lineHeight: 17,
    fontWeight: "400",
    marginTop: 2,
  },
  aiBannerBtnRow: {
    flexDirection: "row",
    gap: 8,
  },
  aiBannerBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1.2,
  },
  aiBannerBtnYes: {
    backgroundColor: "#5080BC",
    borderColor: "#5080BC",
  },
  aiBannerBtnNo: {
    backgroundColor: C.raised,
    borderColor: C.border,
  },
  aiBannerBtnTxtYes: {
    fontSize: 13,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.2,
  },
  aiBannerBtnTxtNo: {
    fontSize: 13,
    fontWeight: "600",
    color: C.soft,
    letterSpacing: 0.2,
  },
  aiBannerDoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  aiBannerDoneTxt: {
    fontSize: 12.5,
    color: C.soft,
    fontWeight: "500",
    flex: 1,
    lineHeight: 17,
  },
});
