import { StyleSheet } from "react-native";

export const C = {
  bg:      "#111111",
  surface: "#1D1D1D",
  raised:  "#262626",
  border:  "#303030",
  text:    "#F2F2F2",
  soft:    "#8A8A8A",
  faint:   "#555555",

  blue:    "#5080BC",
  green:   "#4A8F5A",
  danger:  "#9E4040",

  mBreakfast: "#A87050",
  mLunch:     "#4E7890",
  mDinner:    "#587868",
  mSnacks:    "#887058",
};

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: C.bg,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 52,
    paddingBottom: 12,
  },
  logo: {
    fontSize: 18,
    fontWeight: "700",
    color: C.text,
    letterSpacing: -0.3,
  },
  logoutBtn: {
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  logoutText: {
    fontSize: 13,
    color: C.soft,
    fontWeight: "500",
  },

  pressed: { opacity: 0.45 },

  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dateDivider: {
    height: 1,
    backgroundColor: C.border,
    alignSelf: "center",
    width: 120,
    marginBottom: 4,
  },
  arrowBtn: {
    padding: 6,
  },
  arrowGlyph: {
    fontSize: 22,
    color: C.soft,
    lineHeight: 26,
  },
  dateTouchable: {
    flex: 1,
    alignItems: "center",
  },
  dateText: {
    fontSize: 19,
    fontWeight: "600",
    color: C.text,
    letterSpacing: -0.2,
  },
  dateSub: {
    fontSize: 11,
    color: C.blue,
    marginTop: 2,
    fontWeight: "500",
  },

  calorieCard: {
    margin: 12,
    backgroundColor: C.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  calorieRow: {
    flexDirection: "row",
    paddingVertical: 18,
  },
  calStat: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  calDivider: {
    width: 1,
    backgroundColor: C.border,
    alignSelf: "stretch",
  },
  calValue: {
    fontSize: 28,
    fontWeight: "300",
    fontVariant: ["tabular-nums"],
  },
  calLabel: {
    fontSize: 10,
    color: C.soft,
    fontWeight: "500",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  progressTrack: {
    height: 4,
    backgroundColor: C.raised,
    marginHorizontal: 16,
    borderRadius: 2,
    overflow: "hidden",
  },
  progressFill: {
    height: 4,
    backgroundColor: C.blue,
    borderRadius: 2,
  },
  progressOver: {
    backgroundColor: C.danger,
  },
  insetSep: {
    height: 1,
    backgroundColor: C.border,
    marginHorizontal: 16,
  },
  macroRow: {
    flexDirection: "row",
  },
  macroPill: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    gap: 3,
  },
  macroDivider: {
    width: 1,
    backgroundColor: C.border,
    alignSelf: "stretch",
  },
  macroValue: {
    fontSize: 16,
    fontWeight: "600",
    color: C.text,
    fontVariant: ["tabular-nums"],
  },
  macroLabel: {
    fontSize: 10,
    color: C.soft,
    letterSpacing: 0.5,
  },

  mealList: {
    paddingHorizontal: 14,
    gap: 10,
    marginTop: 8,
  },
  mealCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  mealHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  mealHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mealAccent: {
    width: 3,
    height: 16,
    borderRadius: 2,
  },
  mealLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: C.text,
  },
  mealHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mealCal: {
    fontSize: 14,
    color: C.soft,
    fontVariant: ["tabular-nums"],
  },
  chevron: {
    fontSize: 13,
    color: C.faint,
    marginTop: 1,
  },
  foodList: {},
  foodRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  foodSep: {
    height: 1,
    backgroundColor: C.raised,
    marginHorizontal: 16,
  },
  foodName: {
    flex: 1,
    fontSize: 14,
    color: C.text,
    marginRight: 12,
  },
  foodCal: {
    fontSize: 14,
    color: C.soft,
    fontVariant: ["tabular-nums"],
  },
  addFoodRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addFoodText: {
    fontSize: 14,
    fontWeight: "500",
  },

  searchSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    backgroundColor: C.surface,
    borderTopWidth: 1,
    borderColor: C.border,
    paddingBottom: 40,
  },
  searchDragZone: {
    paddingVertical: 14,
    alignItems: "center",
  },
  searchHandle: {
    width: 36,
    height: 4,
    backgroundColor: C.border,
    borderRadius: 2,
  },
  searchTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  searchTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: C.text,
  },
  searchDone: {
    fontSize: 14,
    color: C.soft,
    fontWeight: "500",
  },
  searchBarWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.raised,
    borderRadius: 10,
    marginHorizontal: 14,
    marginBottom: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  searchIcon: {
    fontSize: 18,
    color: C.soft,
    marginRight: 8,
    marginTop: -1,
  },
  searchInput: {
    flex: 1,
    height: 44,
    fontSize: 15,
    color: C.text,
  },
  searchEmptyState: {
    alignItems: "center",
    paddingTop: 48,
    paddingBottom: 32,
    gap: 8,
  },
  searchEmptyIcon: {
    fontSize: 32,
    color: C.faint,
    marginBottom: 4,
  },
  searchEmptyText: {
    fontSize: 15,
    fontWeight: "600",
    color: C.soft,
  },
  searchEmptySub: {
    fontSize: 13,
    color: C.faint,
  },
  searchSectionLabel: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: C.soft,
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 10,
  },
  searchResultRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  searchResultLeft: {
    flex: 1,
    marginRight: 14,
    gap: 5,
  },
  searchResultName: {
    fontSize: 14,
    fontWeight: "500",
    color: C.text,
  },
  searchResultMacroRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  searchResultMacroChip: {
    fontSize: 11,
    color: C.soft,
    fontVariant: ["tabular-nums"],
  },
  searchResultMacroDot: {
    fontSize: 11,
    color: C.faint,
  },
  searchResultServing: {
    fontSize: 11,
    color: C.faint,
  },
  searchResultCalCol: {
    alignItems: "flex-end",
    gap: 1,
  },
  searchResultCal: {
    fontSize: 16,
    fontWeight: "600",
    color: C.text,
    fontVariant: ["tabular-nums"],
  },
  searchResultCalUnit: {
    fontSize: 10,
    color: C.soft,
    letterSpacing: 0.4,
  },
  searchResultSep: {
    height: 1,
    backgroundColor: C.raised,
    marginHorizontal: 18,
  },

  detailView: {
    flex: 1,
    backgroundColor: C.surface,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 10,
  },
  detailBackBtn: {
    paddingVertical: 6,
    paddingRight: 12,
  },
  detailBackText: {
    fontSize: 16,
    color: C.soft,
    fontWeight: "500",
  },
  detailXBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: C.raised,
    alignItems: "center",
    justifyContent: "center",
  },
  detailXText: {
    fontSize: 14,
    color: C.soft,
    lineHeight: 18,
  },
  detailFoodName: {
    fontSize: 18,
    fontWeight: "700",
    color: C.text,
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 4,
    lineHeight: 24,
  },
  detailServing: {
    fontSize: 13,
    color: C.soft,
    paddingHorizontal: 18,
    paddingBottom: 16,
  },
  detailCalBlock: {
    alignItems: "center",
    paddingVertical: 22,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: C.border,
    marginHorizontal: 18,
    marginBottom: 16,
  },
  detailCalNum: {
    fontSize: 52,
    fontWeight: "200",
    color: C.text,
    fontVariant: ["tabular-nums"],
    lineHeight: 58,
  },
  detailCalLabel: {
    fontSize: 11,
    color: C.soft,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginTop: 4,
  },
  detailSection: {
    marginHorizontal: 18,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: C.raised,
  },
  detailRowIndented: {
    paddingLeft: 24,
    backgroundColor: C.surface,
  },
  detailRowLabel: {
    fontSize: 14,
    color: C.text,
    fontWeight: "500",
  },
  detailRowLabelSoft: {
    color: C.soft,
    fontWeight: "400",
  },
  detailRowValue: {
    fontSize: 14,
    color: C.soft,
    fontVariant: ["tabular-nums"],
  },
  detailDivider: {
    height: 1,
    backgroundColor: C.border,
  },
  detailAllergens: {
    fontSize: 12,
    color: C.faint,
    paddingHorizontal: 18,
    paddingBottom: 16,
    fontStyle: "italic",
  },
  quantitySection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  quantityLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: C.text,
  },
  quantityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  quantityBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.raised,
  },
  quantityBtnText: {
    fontSize: 20,
    color: C.text,
    lineHeight: 24,
  },
  quantityNum: {
    fontSize: 20,
    fontWeight: "600",
    color: C.text,
    minWidth: 28,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  saveBtn: {
    marginHorizontal: 18,
    marginTop: 8,
    marginBottom: 24,
    paddingVertical: 15,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: {
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  deleteBtn: {
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 8,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.danger,
    alignItems: "center",
  },
  deleteBtnText: {
    fontSize: 14,
    fontWeight: "500",
    color: C.danger,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  calendarCard: {
    backgroundColor: C.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    width: "100%",
    padding: 16,
  },
  calMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  calMonthArrow: {
    padding: 8,
  },
  calMonthArrowText: {
    fontSize: 20,
    color: C.soft,
    lineHeight: 24,
  },
  calMonthLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: C.text,
  },
  calGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calDayHeader: {
    width: "14.28%",
    alignItems: "center",
    paddingBottom: 8,
  },
  calDayHeaderText: {
    fontSize: 11,
    fontWeight: "600",
    color: C.soft,
    letterSpacing: 0.5,
  },
  calCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  calCellText: {
    fontSize: 14,
    color: C.text,
  },
  calCellSelected: {
    backgroundColor: C.blue,
    borderRadius: 100,
  },
  calCellSelectedText: {
    color: "#fff",
    fontWeight: "600",
  },
  calCellToday: {
    borderWidth: 1,
    borderColor: C.blue,
    borderRadius: 100,
  },
  calCellTodayText: {
    color: C.blue,
  },
  calCellEmpty: {},

  // ── Nutrition Breakdown Modal ──────────────────────────────────
  nbOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  nbSheet: {
    backgroundColor: C.bg,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderColor: C.border,
    height: "92%",
  },
  nbHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderColor: C.border,
  },
  nbTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: C.text,
    letterSpacing: -0.2,
  },
  nbSubtitle: {
    fontSize: 12,
    color: C.soft,
    marginTop: 3,
  },
  nbCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: C.raised,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  nbCloseText: {
    fontSize: 13,
    color: C.soft,
    lineHeight: 17,
  },
  nbCalBlock: {
    alignItems: "center",
    paddingVertical: 28,
    borderBottomWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 20,
  },
  nbCalNum: {
    fontSize: 64,
    fontWeight: "200",
    color: C.text,
    fontVariant: ["tabular-nums"],
    lineHeight: 70,
  },
  nbCalLabel: {
    fontSize: 11,
    color: C.soft,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginTop: 4,
  },
  nbGoalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 16,
    marginBottom: 8,
  },
  nbGoalText: {
    fontSize: 12,
    color: C.soft,
    fontVariant: ["tabular-nums"],
  },
  nbProgressTrack: {
    height: 4,
    backgroundColor: C.raised,
    width: "100%",
    borderRadius: 2,
    overflow: "hidden",
  },
  nbProgressFill: {
    height: 4,
    backgroundColor: C.green,
    borderRadius: 2,
  },
  nbMacroRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: C.border,
  },
  nbMacroPill: {
    flex: 1,
    paddingVertical: 16,
    alignItems: "center",
    gap: 4,
    backgroundColor: C.surface,
  },
  nbMacroDivider: {
    width: 1,
    backgroundColor: C.border,
    alignSelf: "stretch",
  },
  nbMacroVal: {
    fontSize: 20,
    fontWeight: "600",
    color: C.text,
    fontVariant: ["tabular-nums"],
  },
  nbMacroLbl: {
    fontSize: 10,
    color: C.soft,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  nbModeRow: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 4,
    marginTop: 8,
    backgroundColor: C.raised,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  nbModeBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
  },
  nbModeBtnActive: {
    backgroundColor: C.blue,
  },
  nbModeBtnText: {
    fontSize: 12,
    fontWeight: "500",
    color: C.soft,
  },
  nbModeBtnTextActive: {
    color: "#fff",
    fontWeight: "600",
  },

  nbSectionLabel: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: C.soft,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 10,
  },
});
